language: cpp
compiler:
- gcc
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential qt5-default qttools5-dev-tools freeglut3-dev libsdl2-dev libglew-dev
  - cd platforms/linux/Gearboy
os:
- linux
script:
  - qmake -o Makefile Gearboy.pro && make
dist: xenial
